spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/buff
    username: root
    password: czm20010115
  application:
    name: buffCrawler
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.czm.buffcrawlermaster.pojo
server:
  port: 8081
